/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package group1database;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author JuliusDev
 */
public class AddEditRecord extends javax.swing.JFrame {

    private boolean isEdit;
    private String StudentId;
    private OnSavedEvent ose;
    private String[] arg;
    /**
     * Creates new form AddEditRecord
     * @param isEdit
     * @param ose
     * @param arg
     */
    public AddEditRecord(boolean isEdit, OnSavedEvent ose, String arg[]) {
        initComponents();
        
        if(isEdit){
            aerTitle.setText("Edit Record");
        }else{
            aerTitle.setText("Add Record");
        }
        this.arg = arg;
        this.isEdit = isEdit;
        this.ose = ose;
        if (arg != null){
            StudentId = arg[0];
            txtLn.setText(arg[1]);
            txtFn.setText(arg[2]);
            txtMn.setText(arg[3]);
            txtCourse.setText(arg[4]);
            txtYear.setText(arg[5]);
            txtAddress.setText(arg[6]);
            txtBday.setText(arg[7]);
            txtContact.setText(arg[8]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        aerTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtFn = new javax.swing.JTextField();
        txtMn = new javax.swing.JTextField();
        txtLn = new javax.swing.JTextField();
        txtCourse = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        txtBday = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        aerTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        aerTitle.setForeground(new java.awt.Color(255, 255, 255));
        aerTitle.setText("Add/Edit Record");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(aerTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(aerTitle)
                .addGap(25, 25, 25))
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 526));

        txtFn.setBackground(new java.awt.Color(44, 62, 80));
        txtFn.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtFn.setBorder(javax.swing.BorderFactory.createTitledBorder("First Name:"));
        txtFn.setPreferredSize(new java.awt.Dimension(300, 80));

        txtMn.setBackground(new java.awt.Color(44, 62, 80));
        txtMn.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtMn.setBorder(javax.swing.BorderFactory.createTitledBorder("Middle Name:"));
        txtMn.setPreferredSize(new java.awt.Dimension(300, 80));

        txtLn.setBackground(new java.awt.Color(44, 62, 80));
        txtLn.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtLn.setBorder(javax.swing.BorderFactory.createTitledBorder("Last Name:"));
        txtLn.setPreferredSize(new java.awt.Dimension(300, 80));

        txtCourse.setBackground(new java.awt.Color(44, 62, 80));
        txtCourse.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtCourse.setBorder(javax.swing.BorderFactory.createTitledBorder("Course:"));
        txtCourse.setPreferredSize(new java.awt.Dimension(300, 80));

        txtYear.setBackground(new java.awt.Color(44, 62, 80));
        txtYear.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtYear.setBorder(javax.swing.BorderFactory.createTitledBorder("Year:"));
        txtYear.setPreferredSize(new java.awt.Dimension(300, 80));

        txtContact.setBackground(new java.awt.Color(44, 62, 80));
        txtContact.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtContact.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact:"));
        txtContact.setPreferredSize(new java.awt.Dimension(300, 80));

        txtBday.setBackground(new java.awt.Color(44, 62, 80));
        txtBday.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtBday.setBorder(javax.swing.BorderFactory.createTitledBorder("Birthday:"));
        txtBday.setPreferredSize(new java.awt.Dimension(300, 80));

        txtAddress.setBackground(new java.awt.Color(44, 62, 80));
        txtAddress.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("Address:"));
        txtAddress.setPreferredSize(new java.awt.Dimension(300, 80));

        btnCancel.setText("CANCEL");
        btnCancel.setPreferredSize(new java.awt.Dimension(145, 50));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText("SAVE");
        btnSave.setPreferredSize(new java.awt.Dimension(145, 50));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtFn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtBday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        try {
            Class.forName("org.sqlite.JDBC");

            if (isEdit) {

                Connection con = DriverManager.getConnection("jdbc:sqlite:group1.db");
                String update = "UPDATE STUDINFO SET StudID=?, LastName=?, FirstName=?, MiddleName=?, Course=?, Year=?, Address=?, Birthday=?, Contact=? where StudID=" + StudentId + "";
                PreparedStatement pst = con.prepareStatement(update);
                pst.setString(2, txtLn.getText());
                pst.setString(3, txtFn.getText());
                pst.setString(4, txtMn.getText());
                pst.setString(5, txtCourse.getText());
                pst.setInt(6, Integer.parseInt(txtYear.getText()));
                pst.setString(7, txtAddress.getText());
                pst.setString(8, txtBday.getText());
                pst.setInt(9, Integer.parseInt(txtContact.getText()));

                pst.executeUpdate();
                
            } else {
                try (Connection con = DriverManager.getConnection("jdbc:sqlite:group1.db")) {
                    String insert = "INSERT INTO STUDINFO VALUES(?,?,?,?,?,?,?,?,?)";
                    PreparedStatement pst = con.prepareStatement(insert);
                    pst.setString(2, txtLn.getText());
                    pst.setString(3, txtFn.getText());
                    pst.setString(4, txtMn.getText());
                    pst.setString(5, txtCourse.getText());
                    pst.setInt(6, Integer.parseInt(txtYear.getText()));
                    pst.setString(7, txtAddress.getText());
                    pst.setString(8, txtBday.getText());
                    pst.setString(9, txtContact.getText());

                    pst.execute();
                }
            }

            JOptionPane.showMessageDialog(null, "Saved!");
            ose.onSaved();
            this.setVisible(false);
        } catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
        ose.onCancel();
    }//GEN-LAST:event_btnCancelActionPerformed

    public void showAER() {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            AddEditRecord.this.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aerTitle;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBday;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtFn;
    private javax.swing.JTextField txtLn;
    private javax.swing.JTextField txtMn;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
